(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e=this||self;function f(b,c){b=b.split(".");var a=e;b[0]in a||"undefined"==typeof a.execScript||a.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===c?a[d]&&a[d]!==Object.prototype[d]?a=a[d]:a=a[d]={}:a[d]=c}
;var g={YEAR_FULL:"y",YEAR_FULL_WITH_ERA:"y G",YEAR_MONTH_ABBR:"MMM y",YEAR_MONTH_FULL:"MMMM y",YEAR_MONTH_SHORT:"MM/y",MONTH_DAY_ABBR:"MMM d",MONTH_DAY_FULL:"MMMM dd",MONTH_DAY_SHORT:"M/d",MONTH_DAY_MEDIUM:"MMMM d",MONTH_DAY_YEAR_MEDIUM:"MMM d, y",WEEKDAY_MONTH_DAY_MEDIUM:"EEE, MMM d",WEEKDAY_MONTH_DAY_YEAR_MEDIUM:"EEE, MMM d, y",DAY_ABBR:"d",MONTH_DAY_TIME_ZONE_SHORT:"MMM d, h:mm a zzzz"};
g={YEAR_FULL:"y",YEAR_FULL_WITH_ERA:"y G",YEAR_MONTH_ABBR:"MMM y",YEAR_MONTH_FULL:"MMMM y",YEAR_MONTH_SHORT:"MM/y",MONTH_DAY_ABBR:"d MMM",MONTH_DAY_FULL:"dd MMMM",MONTH_DAY_SHORT:"d/M",MONTH_DAY_MEDIUM:"d MMMM",MONTH_DAY_YEAR_MEDIUM:"d MMM y",WEEKDAY_MONTH_DAY_MEDIUM:"EEE, d MMM",WEEKDAY_MONTH_DAY_YEAR_MEDIUM:"EEE, d MMM y",DAY_ABBR:"d",MONTH_DAY_TIME_ZONE_SHORT:"d MMM HH.mm zzzz"};var h={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
h={ERAS:["SM","M"],ERANAMES:["Sebelum Masehi","Masehi"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"Januari Februari Maret April Mei Juni Juli Agustus September Oktober November Desember".split(" "),STANDALONEMONTHS:"Januari Februari Maret April Mei Juni Juli Agustus September Oktober November Desember".split(" "),SHORTMONTHS:"Jan Feb Mar Apr Mei Jun Jul Agu Sep Okt Nov Des".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr Mei Jun Jul Agu Sep Okt Nov Des".split(" "),
WEEKDAYS:"Minggu Senin Selasa Rabu Kamis Jumat Sabtu".split(" "),STANDALONEWEEKDAYS:"Minggu Senin Selasa Rabu Kamis Jumat Sabtu".split(" "),SHORTWEEKDAYS:"Min Sen Sel Rab Kam Jum Sab".split(" "),STANDALONESHORTWEEKDAYS:"Min Sen Sel Rab Kam Jum Sab".split(" "),NARROWWEEKDAYS:"MSSRKJS".split(""),STANDALONENARROWWEEKDAYS:"MSSRKJS".split(""),SHORTQUARTERS:["K1","K2","K3","K4"],QUARTERS:["Kuartal ke-1","Kuartal ke-2","Kuartal ke-3","Kuartal ke-4"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, dd MMMM y","d MMMM y",
"d MMM y","dd/MM/yy"],TIMEFORMATS:["HH.mm.ss zzzz","HH.mm.ss z","HH.mm.ss","HH.mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};function k(b,c){if(void 0===c){c=b+"";var a=c.indexOf(".");c=Math.min(-1===a?0:c.length-a-1,3)}return 1==(b|0)&&0==c?"one":"other"}
k=function(){return"other"};f("YT_I18N_FORMATTING_GOOG_LOCALE","id");f("YT_I18N_FORMATTING_DATE_TIME_PATTERNS",g);f("YT_I18N_FORMATTING_DATE_TIME_SYMBOLS",h);
f("YT_I18N_FORMATTING_RELATIVE_DATE_TIME_SYMBOLS",{DAY:{LONG:{R:{"-1":"kemarin","-2":"kemarin dulu",0:"hari ini",1:"besok",2:"lusa"},P:"other{# hari yang lalu}",F:"other{dalam # hari}"},SHORT:{R:{"-2":"selumbari",2:"lusa"},P:"other{# h lalu}",F:"other{dalam # h}"},NARROW:{R:{2:"lusa"},P:"other{# h lalu}",F:"other{dalam # h}"}},HOUR:{LONG:{R:{0:"jam ini"},P:"other{# jam yang lalu}",F:"other{dalam # jam}"},SHORT:{R:{0:"jam ini"},P:"other{# jam lalu}",F:"other{dalam # jam}"}},MINUTE:{LONG:{R:{0:"menit ini"},
P:"other{# menit yang lalu}",F:"other{dalam # menit}"},SHORT:{R:{0:"mnt ini"},P:"other{# mnt lalu}",F:"other{dlm # mnt}"}},MONTH:{LONG:{R:{"-1":"bulan lalu",0:"bulan ini",1:"bulan depan"},P:"other{# bulan yang lalu}",F:"other{dalam # bulan}"},SHORT:{R:{"-1":"bln lalu",0:"bln ini",1:"bln berikutnya"},P:"other{# bln lalu}",F:"other{dlm # bln}"}},QUARTER:{LONG:{R:{"-1":"Kuartal lalu",0:"kuartal ini",1:"kuartal berikutnya"},P:"other{# kuartal yang lalu}",F:"other{dalam # kuartal}"},SHORT:{R:{"-1":"krtl lalu",
0:"krtl ini",1:"krtl berikutnya"},P:"other{# krtl. lalu}",F:"other{dlm # krtl.}"}},SECOND:{LONG:{R:{0:"sekarang"},P:"other{# detik yang lalu}",F:"other{dalam # detik}"},SHORT:{R:{0:"sekarang"},P:"other{# dtk lalu}",F:"other{dlm # dtk}"}},WEEK:{LONG:{R:{"-1":"minggu lalu",0:"minggu ini",1:"minggu depan"},P:"other{# minggu yang lalu}",F:"other{dalam # minggu}"},SHORT:{R:{"-1":"mgg lalu",0:"mgg ini",1:"mgg depan"},P:"other{# mgg lalu}",F:"other{dlm # mgg}"}},YEAR:{LONG:{R:{"-1":"tahun lalu",0:"tahun ini",
1:"tahun depan"},P:"other{# tahun yang lalu}",F:"other{dalam # tahun}"},SHORT:{R:{"-1":"thn lalu",0:"thn ini",1:"thn depan"},P:"other{# thn lalu}",F:"other{dlm # thn}"}}});f("YT_I18N_FORMATTING_PLURAL_RULES_SELECT",k);}).call(this);
